services:
  workspace:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file: .env
    networks:
      - private
    environment:
      - http_proxy=http://proxy:3128
      - https_proxy=http://proxy:3128
      - no_proxy=localhost,127.0.0.1,proxy

  proxy:
      image: ubuntu/squid
      volumes:
        - ./squid.conf:/etc/squid/squid.conf:ro
        - ./allowed-sites.txt:/etc/squid/allowed-sites.txt:ro
      networks:
        - private
        - public

networks:
  public:
  private:
    internal: true
