services:
  workspace:
    build: .
    volumes:
      - ./projects:/projects
    working_dir: /projects
    env_file: .env
    networks:
      - private

  proxy:
      image: ubuntu/squid
      volumes:
        - ./squid.conf:/etc/squid/squid.conf:ro
        - ./allowed-sites.txt:/etc/squid/allowed-sites.txt:ro
      networks:
        - private
        - public

networks:
  public:
  private:
    internal: true
