http_port 3128

acl allowed_domains dstdomain "/etc/squid/allowed-sites.txt"
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16

acl CONNECT method CONNECT

http_access allow localnet allowed_domains
http_access deny all